# Generated by Django 5.0.2 on 2024-03-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
