# Generated by Django 5.0.2 on 2024-03-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='ecapp/static/img/blog', verbose_name='')),
            ],
        ),
    ]
